// enum TagsNames {
//   mediawiki,
//   siteinfo,
//   sitename,
//   dbname,
//   base,
//   generator,
//   case,
//   namespaces,
//   namespace,
//   page,
//   title,
//   ns,
//   id,
//   revision,
//   timestamp,
//   contributor,
//   username,
//   ip,
//   model,
//   minor,
//   comment,
//   format,
//   text,
//   sha1,
// }
const TagsNames = {
  0: 'mediawiki',
  1: 'siteinfo',
  3: 'sitename',
  4: 'dbname',
  5: 'base',
  6: 'generator',
  7: 'case',
  8: 'namespaces',
  9: 'namespace',
  10: 'page',
  11: 'title',
  12: 'ns',
  13: 'id',
  14: 'revision',
  15: 'timestamp',
  16: 'contributor',
  17: 'username',
  18: 'ip',
  19: 'model',
  20: 'minor',
  21: 'comment',
  22: 'format',
  23: 'text',
  24: 'sha1',
  25: 'minor',
};

export default () => TagsNames;
